// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NovelaidDirEntry = { name: string, isDirectory: boolean, documentType: NovelaidDocumentType, children: Array<NovelaidDirEntry> | null, };

export type NovelaidDocumentType = "novel" | "markdown" | "image" | "chat" | "gitDiff" | "browser" | "css" | "unknown" | "external";
