[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-ping",
    "allow-get-document-type",
    "allow-get-directory-type",
    "allow-read-directory",
    "allow-set-project-directory",
    "allow-get-project-directory",
]
